### ISSUE TITLE
Wont compile on 4.7+

### ISSUE THREAD

**Issue by plopplopplop** [dsiggi/RocketRAID#2]
I suppose partially because of https://lkml.org/lkml/2016/2/25/664 or https://lkml.org/lkml/2016/5/18/680 :

```
  CC [M]  /var/lib/dkms/rr2340/1.7/build/product/rr2340/linux/.build/osm_linux.o
/var/lib/dkms/rr2340/1.7/build/product/rr2340/linux/.build/os_linux.c: In function 'refresh_sd_flags':
/var/lib/dkms/rr2340/1.7/build/product/rr2340/linux/.build/os_linux.c:278:41: error: 'struct gendisk' has no member named 'driverfs_dev'
       if (bdev->bd_disk && bdev->bd_disk->driverfs_dev==&SDptr->sdev_gendev) {
                                         ^
/var/lib/dkms/rr2340/1.7/build/product/rr2340/linux/.build/os_linux.c:283:35: error: 'struct inode' has no member named 'i_mutex'
         mutex_lock(&bdev->bd_inode->i_mutex);
                                   ^
/var/lib/dkms/rr2340/1.7/build/product/rr2340/linux/.build/os_linux.c:289:37: error: 'struct inode' has no member named 'i_mutex'
         mutex_unlock(&bdev->bd_inode->i_mutex);
                                     ^
```

If you can look into that, that would be most appreciated.

**Comment by dsiggi** [comment]
Hi,
please test the **"sys-block/rr2340-1.7_p20161212"** ebuild. The compiling is working. But I don't know if the module is working. When it's working I can do the changes to all modules.

**Comment by plopplopplop** [comment]
thanks for that.
Shouldnt mutex_lock() be converted to inode_lock() ?

**Comment by dsiggi** [comment]
You're right. I will change it when I'm at home.

**Comment by dsiggi** [comment]
I converted mutex_lock() to indode_lock(). 
I have no idea of c++. So I hope it will work.
Please test and let me know.

**Comment by dsiggi** [comment]
Okay,
the thing with si mutex/inode is now right, I think.
But I don't know how to get the driverfs_dev thing to work.

**Comment by dsiggi** [comment]
I wrote a mail to HighPoint.
Maybe they will update their drivers.
We will see.

**Comment by plopplopplop** [comment]
Good luck with that. They never have, they never will :)

**Comment by dsiggi** [comment]
I found a Thread on forums.opensuse.org: [](https://forums.opensuse.org/showthread.php/519259-Here-is-an-unofficial-driver-patch-for-the-quot-RocketRaid-232x-quot-!-(kernel-4-x))
So I write an PN to dlder. His brother written a new patch for kernels >=4.7.
He send it to me and I can build the driver without problems on my laptop.
On the weekend I will test it on my server and when all works I will update all ebuilds.

**Comment by dsiggi** [comment]
I've updatet the rr2340 driver. The module will now build with kernel >=4.7.
Thank's ro dlder and his brother for the patch: https://forums.opensuse.org/showthread.php/519259-Here-is-an-unofficial-driver-patch-for-the-quot-RocketRaid-232x-quot-!-(kernel-4-x)
I will update the other ebuilds next  week.

Commit 54c2bc31fed4351817ac9a900274286830c727e7 closes #2
